### PR TITLE
Support INTERAC, and SQUARE_GIFT_CARD_V2 in V1 API

### PR DESCRIPTION
**Pull request by sheam**
If you are using webhooks, they will fail as .net can't deserialize the payload when the payment type is INTERAC or SQUARE_GIFT_CARD_V2.

I have been using this mod since 2.61 without issue.

### CODE REVIEW

**Comment by sheam** [comment]
Hello?

**Comment by shaofu88** [comment]
sheam, Thank for you reporting this issue we are working on it. Thanks again.

**Comment by bwisem** [comment]
Hi Sheam, 

Thanks again for reporting this. Would you mind emailing developers@help-messaging.squareup.com so we can work with you to resolve this? 

Cheers!

**Comment by alecholmes** [comment]
Thanks for raising this issue, @sheam. We have made a change on the server so that only the values already defined in `V1Tender.CardBrandEnum` will be returned. We opted to make this change on the server instead of the client in order to not break users who do not upgrade their C# SDKs.

**Comment by sheam** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  So how can tell if a payment is INTERAC now? What about historical payments that already had INTERAC for CardBrand?                                                                                                                                                                        ~Shea                                                                                                                                                                           From: notifications@github.comSent: June 13, 2018 10:52 AMTo: connect-csharp-sdk@noreply.github.comReply to: reply@reply.github.comCc: shea.martin@gmail.com; mention@noreply.github.comSubject: Re: [square/connect-csharp-sdk] Support INTERAC, and SQUARE_GIFT_CARD_V2 in V1 API (#61)  Thanks for raising this issue, @sheam. We have made a change on the server so that only the values already defined in V1Tender.CardBrandEnum will be returned. We opted to make this change on the server instead of the client in order to not break users who do not upgrade their C# SDKs.

**Comment by alecholmes** [comment]
Currently there is not a way to tell if a payment is Interact. They will be returned as `OTHER_BRAND`. However, we are working on an approach to add new values to our SDKs without breaking existing users.

**Comment by sheam** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  thanks Alec, I appreciate the update.I had modified the sdk to work with the interac enum. I guess that will no longer work. I guess I can likely assume the type OTHER_BRAND is INTERAC for now.                                                                                                                                                                        ~Shea                                                                                                                                                                           From: notifications@github.comSent: June 13, 2018 12:08 PMTo: connect-csharp-sdk@noreply.github.comReply to: reply@reply.github.comCc: shea.martin@gmail.com; mention@noreply.github.comSubject: Re: [square/connect-csharp-sdk] Support INTERAC, and SQUARE_GIFT_CARD_V2 in V1 API (#61)  Currently there is not a way to tell if a payment is Interact. They will be returned as OTHER_BRAND. However, we are working on an approach to add new values to our SDKs without breaking existing users.

**Comment by sheam** [comment]
Is this still broken? Or should I continue to use my fork?

**Comment by sheam** [comment]
> Currently there is not a way to tell if a payment is Interact. They will be returned as `OTHER_BRAND`. However, we are working on an approach to add new values to our SDKs without breaking existing users.

By OTHER_BRAND do you mean `CardBrandEnum.OTHERBRAND`?

**Comment by StephenJosey** [comment]
Yes OTHER_BRAND == `CardBrandEnum.OTHERBRAND`. Interact payments will still be returned as OTHER_BRAND currently.

**Pull request closed without merging**
